default:
  tags:
    - search

stages:
  - test

variables:
  PIP_REQUIREMENTS_FILE: "requirements-converted.txt"

.poetry:
  image: python:3.9

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    key:
      files:
        - poetry.lock
    paths:
      - .cache/pip

  before_script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install -E azure -E gcp --no-ansi --no-interaction -vv
    - source `poetry env info --path`/bin/activate

lint:
  extends: .poetry
  stage: test
  script:
    - flake8 src/
    - mypy -p censys.cloud_connectors

.test-template:
  extends: .poetry
  stage: test
  script: pytest

unit tests:
  extends: .test-template
  image: python:3.9
  script: pytest --cov --cov-report xml
  artifacts:
    reports:
      cobertura: coverage.xml

scan helm chart - CVE:
  stage: test
  image: gcr.io/censys-internal/censys.io/helm3-ci:2022-01-24_03-21-30
  needs: []
  script:
    - cd kubernetes
    - helm template censys-cloud-connectors ./censys-cloud-connectors --dry-run |  kubescape scan framework nsa -

scan helm chart - Deprecation:
  stage: test
  image: gcr.io/censys-internal/censys.io/helm3-ci:2022-01-24_03-21-30
  needs: []
  script:
    - cd kubernetes
    - helm template censys-cloud-connectors ./censys-cloud-connectors --dry-run | kubent --helm2=false --helm3=false --cluster=false -f -

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

sast:
  stage: test
  variables:
    SEARCH_MAX_DEPTH: "10"

kics-iac-sast:
  stage: test

secret_detection:
  stage: test
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

license_scanning:
  stage: test

gemnasium-python-dependency_scanning:
  stage: test
  before_script:
    - pip install poetry
    - poetry export --output="$PIP_REQUIREMENTS_FILE"
    - rm poetry.lock pyproject.toml
  # Triggers artifacts download, until https://gitlab.com/gitlab-org/gitlab/-/issues/249569 is implemented
