default:
  tags:
    - censec

stages:
  - quality
  - test
  - security

.poetry:
  image: python:3.9

  cache:
    key:
      files:
        - poetry.lock
    paths:
      - .venv
      - .cache/pip

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  before_script:
    - apt-get update
    - apt-get install --assume-yes --no-install-recommends npm
    - pip install --upgrade pip poetry
    - poetry config virtualenvs.in-project true
    - poetry install -E azure -E gcp -vv
    - . .venv/bin/activate

check-flake8: # This job also runs in the quality stage.
  extends: .poetry
  stage: quality
  script:
    - flake8 src/

check-mypy: # This job runs in the quality stage.
  extends: .poetry
  stage: quality # It can run at the same time as quality-job: (in parallel).
  allow_failure: true
  script:
    - mypy -p censys.cloud_connectors

.test-template: # This job runs in the test stage.
  extends: .poetry
  stage: test
  script:
    - pytest
  variables:
    CENSYS_API_KEY: "ci-censys-api-key-xxxxxxxxxxxxxxxxxx"

python3.9:
  extends: .test-template
  image: python:3.9

# python3.10:
#   extends: .test-template
#   image: python:3.10

sast:
  stage: security
  variables:
    SEARCH_MAX_DEPTH: "10"

kics-iac-sast:
  stage: security

secret_detection:
  stage: security
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

gemnasium-python-dependency_scanning:
  stage: security
  # Work around https://gitlab.com/gitlab-org/gitlab/-/issues/7006
  before_script:
    - pip install poetry
    - poetry export --format=requirements.txt --output=requirements.txt
    - rm poetry.lock pyproject.toml

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
