version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry 1.2.2
      - asdf global poetry 1.2.2
      - poetry config virtualenvs.create false
      - poetry export --with docs --format=requirements.txt --output=docs-requirements.txt

python:
  install:
    - method: pip
      path: .
    - requirements: docs-requirements.txt

formats:
  - pdf

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
