version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry 1.2.2
      - asdf global poetry 1.2.2
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
