# docker-compose -f docker-compose.compare.yml up
version: "3.8"

services:
  # Workspace 1
  censys_cloud_connector_1:
    image: gcr.io/censys-io/censys-cloud-connector:v3.1.3
    volumes:
      - ./providers.compare.yml:/app/providers.yml
      - ./secrets:/app/secrets
    environment:
      CENSYS_API_KEY: ${CENSYS_API_KEY_1}

  # Workspace 2
  censys_cloud_connector_2:
    image: gcr.io/censys-io/censys-cloud-connector:latest
    volumes:
      - ./providers.compare.yml:/app/providers.yml
      - ./secrets:/app/secrets
    environment:
      CENSYS_API_KEY: ${CENSYS_API_KEY_2}
